# Generated by Django 4.2.7 on 2023-11-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField(default=16)),
                ('max_age', models.PositiveIntegerField(default=40)),
                ('min_players', models.PositiveIntegerField(default=15)),
                ('max_players', models.PositiveIntegerField(default=40)),
                ('max_foreign_players', models.PositiveIntegerField(default=10)),
                ('win_points', models.IntegerField(default=3)),
                ('loss_points', models.IntegerField(default=0)),
                ('draw_points', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=90)),
            ],
        ),
    ]
