# Generated by Django 4.2.7 on 2023-11-26 04:45

from django.db import migrations

def create_regulation(apps, schema_editor):
    Regulation = apps.get_model('more', 'Regulation')
    Regulation.objects.create()

class Migration(migrations.Migration):
    
    dependencies = [
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_regulation),
    ]
