# Generated by Django 4.2.7 on 2023-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0002_create_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulation',
            old_name='max_age',
            new_name='player_max_age',
        ),
        migrations.RenameField(
            model_name='regulation',
            old_name='min_age',
            new_name='player_min_age',
        ),
        migrations.AddField(
            model_name='regulation',
            name='manager_max_age',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='regulation',
            name='manager_min_age',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
