# Generated by Django 4.2.7 on 2023-11-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('nationality', models.CharField(choices=[('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Argentina', 'Argentina'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Brazil', 'Brazil'), ('Burkina Faso', 'Burkina Faso'), ('Cameroon', 'Cameroon'), ('Colombia', 'Colombia'), ('Congo DR', 'Congo DR'), ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Côte d`Ivoire', 'Côte d`Ivoire'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('England', 'England'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Guinea', 'Guinea'), ('IR Iran', 'IR Iran'), ('Iraq', 'Iraq'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Korea Republic', 'Korea Republic'), ('Liberia', 'Liberia'), ('Mexico', 'Mexico'), ('Mali', 'Mali'), ('Montenegro', 'Montenegro'), ('Montserrat', 'Montserrat'), ('Morocco', 'Morocco'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Nigeria', 'Nigeria'), ('Northern Ireland', 'Northern Ireland'), ('Norway', 'Norway'), ('Paraguay', 'Paraguay'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Republic of Ireland', 'Republic of Ireland'), ('Senegal', 'Senegal'), ('Scotland', 'Scotland'), ('Serbia', 'Serbia'), ('Slovakia', 'Slovakia'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Tunisia', 'Tunisia'), ('Turkiye', 'Turkiye'), ('Ukraine', 'Ukraine'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela'), ('Wales', 'Wales'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=3)),
                ('image', models.ImageField(blank=True, upload_to='player_imgs/')),
                ('type', models.CharField(choices=[('HG', 'Homegrown'), ('FR', 'Foreign')], default='HG', max_length=2)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='players.player')),
            ],
        ),
    ]
