# Generated by Django 4.2.7 on 2023-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(choices=[('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('Argentinian', 'Argentinian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Belgian', 'Belgian'), ('Bosnian', 'Bosnian'), ('Brazilian', 'Brazilian'), ('Burkinabe', 'Burkinabe'), ('Cameroonian', 'Cameroonian'), ('Colombian', 'Colombian'), ('Congolese', 'Congolese'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Ivorian', 'Ivorian'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Ecuadorian', 'Ecuadorian'), ('Egyptian', 'Egyptian'), ('English', 'English'), ('Estonian', 'Estonian'), ('Finnish', 'Finnish'), ('French', 'French'), ('Gabonese', 'Gabonese'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Greek', 'Greek'), ('Grenadian', 'Grenadian'), ('Guinean', 'Guinean'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Israeli', 'Israeli'), ('Italian', 'Italian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('South Korean', 'South Korean'), ('Liberian', 'Liberian'), ('Mexican', 'Mexican'), ('Malian', 'Malian'), ('Montenegrin', 'Montenegrin'), ('Montserratian', 'Montserratian'), ('Moroccan', 'Moroccan'), ('Dutch', 'Dutch'), ('New Zealander', 'New Zealander'), ('Nigerian', 'Nigerian'), ('Northern Irish', 'Northern Irish'), ('Norwegian', 'Norwegian'), ('Paraguayan', 'Paraguayan'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Irish', 'Irish'), ('Senegalese', 'Senegalese'), ('Scottish', 'Scottish'), ('Serbian', 'Serbian'), ('Slovak', 'Slovak'), ('Spanish', 'Spanish'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Ukrainian', 'Ukrainian'), ('American', 'American'), ('Uruguayan', 'Uruguayan'), ('Venezuelan', 'Venezuelan'), ('Welsh', 'Welsh'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean')], max_length=30),
        ),
    ]
