# Generated by Django 4.2.7 on 2023-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('V', 'Valid'), ('I', 'Invalid')], default='I', max_length=2),
        ),
    ]
