# Generated by Django 4.2.7 on 2023-11-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_established_year_club_location_club_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, choices=[('BA', 'Bath'), ('BI', 'Birmingham'), ('BR', 'Bradford'), ('BH', 'Brighton and Hove'), ('BU', 'Bristol'), ('CA', 'Cambridge'), ('CN', 'Canterbury'), ('CR', 'Carlisle'), ('CM', 'Chelmsford'), ('CH', 'Chester'), ('CI', 'Chichester'), ('CO', 'Colchester'), ('CV', 'Coventry'), ('DE', 'Derby'), ('DO', 'Doncaster'), ('DU', 'Durham'), ('EL', 'Ely'), ('EX', 'Exeter'), ('GL', 'Gloucester'), ('HE', 'Hereford'), ('HU', 'Kingston upon Hull'), ('LA', 'Lancaster'), ('LE', 'Leeds'), ('LI', 'Leicester'), ('LC', 'Lichfield'), ('LN', 'Lincoln'), ('LV', 'Liverpool'), ('LO', 'London'), ('MA', 'Manchester'), ('MK', 'Milton Keynes'), ('NE', 'Newcastle upon Tyne'), ('NO', 'Norwich'), ('NG', 'Nottingham'), ('OX', 'Oxford'), ('PE', 'Peterborough'), ('PL', 'Plymouth'), ('PO', 'Portsmouth'), ('PR', 'Preston'), ('RI', 'Ripon'), ('SA', 'Salford'), ('SB', 'Salisbury'), ('SH', 'Sheffield'), ('SO', 'Southampton'), ('SE', 'Southend-on-Sea'), ('ST', 'St Albans'), ('SN', 'Stoke-on-Trent'), ('SU', 'Sunderland'), ('TR', 'Truro'), ('WA', 'Wakefield'), ('WE', 'Wells'), ('WS', 'Westminster'), ('WI', 'Winchester'), ('WO', 'Wolverhampton'), ('WR', 'Worcester'), ('YO', 'York')], default='', max_length=2),
        ),
    ]
