NATIONALITY_CHOICES = [
    ('Albania', 'Albania'),
    ('Algeria', 'Algeria'),
    ('Argentina', 'Argentina'),
    ('Australia', 'Australia'),
    ('Austria', 'Austria'),
    ('Belgium', 'Belgium'),
    ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
    ('Brazil', 'Brazil'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Cameroon', 'Cameroon'),
    ('Colombia', 'Colombia'),
    ('Congo DR', 'Congo DR'),
    ('Costa Rica', 'Costa Rica'),
    ('Croatia', 'Croatia'),
    ('Côte d`Ivoire', 'Côte d`Ivoire'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Ecuador', 'Ecuador'),
    ('Egypt', 'Egypt'),
    ('England', 'England'),
    ('Estonia', 'Estonia'),
    ('Finland', 'Finland'),
    ('France', 'France'),
    ('Gabon', 'Gabon'),
    ('Germany', 'Germany'),
    ('Ghana', 'Ghana'),
    ('Greece', 'Greece'),
    ('Grenada', 'Grenada'),
    ('Guinea', 'Guinea'),
    ('IR Iran', 'IR Iran'),
    ('Iraq', 'Iraq'),
    ('Israel', 'Israel'),
    ('Italy', 'Italy'),
    ('Jamaica', 'Jamaica'),
    ('Japan', 'Japan'),
    ('Korea Republic', 'Korea Republic'),
    ('Liberia', 'Liberia'),
    ('Mexico', 'Mexico'),
    ('Mali', 'Mali'),
    ('Montenegro', 'Montenegro'),
    ('Montserrat', 'Montserrat'),
    ('Morocco', 'Morocco'),
    ('Netherlands', 'Netherlands'),
    ('New Zealand', 'New Zealand'),
    ('Nigeria', 'Nigeria'),
    ('Northern Ireland', 'Northern Ireland'),
    ('Norway', 'Norway'),
    ('Paraguay', 'Paraguay'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Republic of Ireland', 'Republic of Ireland'),
    ('Senegal', 'Senegal'),
    ('Scotland', 'Scotland'),
    ('Serbia', 'Serbia'),
    ('Slovakia', 'Slovakia'),
    ('Spain', 'Spain'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Tunisia', 'Tunisia'),
    ('Turkiye', 'Turkiye'),
    ('Ukraine', 'Ukraine'),
    ('United States', 'United States'),
    ('Uruguay', 'Uruguay'),
    ('Venezuela', 'Venezuela'),
    ('Wales', 'Wales'),
    ('Zambia', 'Zambia'),
    ('Zimbabwe', 'Zimbabwe'),
]

POSITION_CHOICES = [
    ('GK', 'Goalkeeper'),
    ('DF', 'Defender'),
    ('MF', 'Midfielder'),
    ('FW', 'Forward'),
]

TYPE_CHOICES = [
    ('HG', 'Homegrown'),
    ('FR', 'Foreign'),
]