# Generated by Django 4.2.7 on 2023-11-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField()),
                ('stadium', models.CharField(choices=[('AN', 'Anfield'), ('BC', 'Brentford Community Stadium'), ('CG', 'City Ground'), ('CN', 'Carrow Road'), ('CF', 'Craven Cottage'), ('DC', 'Dean Court'), ('EL', 'Elland Road'), ('ES', 'Emirates Stadium'), ('ET', 'Etihad Stadium'), ('GP', 'Goodisan Park'), ('KP', 'King Power Stadium'), ('LS', 'London Stadium'), ('MS', 'Molineux Stadium'), ('OT', 'Old Trafford'), ('SP', 'Selhurst Park'), ('SJ', 'St James Park'), ('SM', "St Mary's Stadium"), ('SB', 'Stamford Bridge'), ('TA', 'The Amex'), ('TH', 'Tottenham Hotspur Stadium'), ('TM', 'Turf Moor'), ('VR', 'Vicarage Road'), ('VP', 'Villa Park')], max_length=2)),
                ('status', models.CharField(choices=[('P', 'Previous'), ('U', 'Upcoming')], max_length=1)),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club1', to='clubs.club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club2', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club1_goals', models.PositiveIntegerField()),
                ('club2_goals', models.PositiveIntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Normal'), ('FK', 'Free kick'), ('OG', 'Own goal')], default='N', max_length=3)),
                ('time', models.PositiveSmallIntegerField()),
                ('assisting_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assisting_event', to='players.player')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('scoring_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_event', to='players.player')),
            ],
        ),
    ]
