# Generated by Django 4.2.7 on 2023-12-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_goalevent_match_alter_result_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalevent',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_event', to='matches.match'),
        ),
    ]
